In [1]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

from bs4 import BeautifulSoup

import pandas as pd
import time

C:\Users\monis\AppData\Roaming\Python\Python314\site-packages\requests\__init__.py:113: RequestsDependencyWarning: urllib3 (2.6.3) or chardet (6.0.0.post1)/charset_normalizer (3.4.4) doesn't match a supported version!
  warnings.warn(

In [2]:
roles = [

    "data-analyst",
    "business-analyst",
    "data-engineer",
    "data-scientist",
    "power-bi-developer",

    "python-developer",
    "java-developer",
    "full-stack-developer",

    "software-tester",
    "automation-tester",
    "selenium-tester",
    "qa-engineer",
    "sdet",

    "devops-engineer",
    "cloud-engineer",

    "cyber-security-analyst",

    "project-manager",

    "fresher-jobs",

    "associate-software-engineer"
]

In [29]:
# Launch browser

driver = webdriver.Chrome(
    service=Service(ChromeDriverManager().install())
)

In [30]:
# Main Scraping Loop

all_jobs = []

for role in roles:

    print(f"\nStarting role: {role}")

    search_role = role.replace("-", "%20")

    for page in range(1, 2):

        url = f"https://www.timesjobs.com/candidate/job-search.html?searchType=personalizedSearch&from=submit&txtKeywords={search_role}&txtLocation=&sequence={page}&startPage={page}"
        
        print(driver.current_url)

        driver.get(url)

        time.sleep(4)

        soup = BeautifulSoup(
            driver.page_source,
            "html.parser"
        )

        job_cards = soup.find_all(
            "div",
            class_="srp-card"
        )

        print("Jobs found:", len(job_cards))


        for card in job_cards:

            # Job Title
            title_tag = card.find("h2")


            # Company + Posted Date
            company_tag = card.find(
                "div",
                class_="text-xs text-gray-400 flex items-center"
            )

            company_text = (
                company_tag.get_text(strip=True)
                if company_tag else ""
            )


            # Split Company and Posted Date
            company_name = (
                company_text.split("|")[0]
                if "|" in company_text else company_text
            )

            posted_date = (
                company_text.split("|")[-1]
                if "|" in company_text else None
            )


            # Full Card Text
            full_text = card.get_text(" ", strip=True)


            # Experience
            exp = None

            for part in full_text.split():

                if "Yrs" in part:

                    exp = part
                    break


            # Salary
            salary = None

            if "LPA" in full_text:

                salary = (
                    full_text.split("LPA")[0][-20:]
                    + " LPA"
                )


            # Apply Link
            link_tag = card.find("a")

            link = (
                link_tag.get("href")
                if link_tag else None
            )


            # Store Data
            all_jobs.append({

                "Portal_Name": "TimesJobs",

                "Role_Search": role,

                "Job_Title":
                title_tag.get_text(strip=True)
                if title_tag else None,

                "Company_Name":
                company_name,

                "Experience_Required":
                exp,

                "Salary":
                salary,

                "Location": None,

                "Skills_Required": None,

                "Posted_Date":
                posted_date,

                "Job_Description":
                full_text[:1000],

                "Company_Rating": None,

                "Reviews_Count": None,

                "Job_Type": None,

                "Company_Size": None,

                "Industry": None,

                "Apply_Link": link
            })

print("Scraping completed")

Starting role: data-analyst
data:,
Jobs found: 10

Starting role: business-analyst
https://www.timesjobs.com/job-search?searchType=personalizedSearch&from=submit&txtKeywords=data+analyst&txtLocation=&sequence=1&startPage=1&refreshed=true
Jobs found: 10

Starting role: data-engineer
https://www.timesjobs.com/job-search?searchType=personalizedSearch&from=submit&txtKeywords=business+analyst&txtLocation=&sequence=1&startPage=1&refreshed=true
Jobs found: 10

Starting role: data-scientist
https://www.timesjobs.com/job-search?searchType=personalizedSearch&from=submit&txtKeywords=data+engineer&txtLocation=&sequence=1&startPage=1&refreshed=true
Jobs found: 10

Starting role: power-bi-developer
https://www.timesjobs.com/job-search?searchType=personalizedSearch&from=submit&txtKeywords=data+scientist&txtLocation=&sequence=1&startPage=1&refreshed=true
Jobs found: 10

Starting role: python-developer
https://www.timesjobs.com/job-search?searchType=personalizedSearch&from=submit&txtKeywords=power+bi+developer&txtLocation=&sequence=1&startPage=1&refreshed=true
Jobs found: 10

Starting role: java-developer
https://www.timesjobs.com/job-search?searchType=personalizedSearch&from=submit&txtKeywords=python+developer&txtLocation=&sequence=1&startPage=1&refreshed=true
Jobs found: 10

Starting role: full-stack-developer
https://www.timesjobs.com/job-search?searchType=personalizedSearch&from=submit&txtKeywords=java+developer&txtLocation=&sequence=1&startPage=1&refreshed=true
Jobs found: 10

Starting role: software-tester
https://www.timesjobs.com/job-search?searchType=personalizedSearch&from=submit&txtKeywords=full+stack+developer&txtLocation=&sequence=1&startPage=1&refreshed=true
Jobs found: 10

Starting role: automation-tester
https://www.timesjobs.com/job-search?searchType=personalizedSearch&from=submit&txtKeywords=software+tester&txtLocation=&sequence=1&startPage=1&refreshed=true
Jobs found: 10

Starting role: selenium-tester
https://www.timesjobs.com/job-search?searchType=personalizedSearch&from=submit&txtKeywords=automation+tester&txtLocation=&sequence=1&startPage=1&refreshed=true
Jobs found: 10

Starting role: qa-engineer
https://www.timesjobs.com/job-search?searchType=personalizedSearch&from=submit&txtKeywords=selenium+tester&txtLocation=&sequence=1&startPage=1&refreshed=true
Jobs found: 10

Starting role: sdet
https://www.timesjobs.com/job-search?searchType=personalizedSearch&from=submit&txtKeywords=qa+engineer&txtLocation=&sequence=1&startPage=1&refreshed=true
Jobs found: 10

Starting role: devops-engineer
https://www.timesjobs.com/job-search?searchType=personalizedSearch&from=submit&txtKeywords=sdet&txtLocation=&sequence=1&startPage=1&refreshed=true
Jobs found: 10

Starting role: cloud-engineer
https://www.timesjobs.com/job-search?searchType=personalizedSearch&from=submit&txtKeywords=devops+engineer&txtLocation=&sequence=1&startPage=1&refreshed=true
Jobs found: 10

Starting role: cyber-security-analyst
https://www.timesjobs.com/job-search?searchType=personalizedSearch&from=submit&txtKeywords=cloud+engineer&txtLocation=&sequence=1&startPage=1&refreshed=true
Jobs found: 10

Starting role: project-manager
https://www.timesjobs.com/job-search?searchType=personalizedSearch&from=submit&txtKeywords=cyber+security+analyst&txtLocation=&sequence=1&startPage=1&refreshed=true
Jobs found: 10

Starting role: fresher-jobs
https://www.timesjobs.com/job-search?searchType=personalizedSearch&from=submit&txtKeywords=project+manager&txtLocation=&sequence=1&startPage=1&refreshed=true
Jobs found: 10

Starting role: associate-software-engineer
https://www.timesjobs.com/job-search?searchType=personalizedSearch&from=submit&txtKeywords=fresher+jobs&txtLocation=&sequence=1&startPage=1&refreshed=true
Jobs found: 10
Scraping completed

In [31]:
driver.quit()

In [35]:
# creating data frame

df = pd.DataFrame(all_jobs)

print(df.shape)

df.head()

(190, 16)

,Portal_Name,Role_Search,Job_Title,Company_Name,Experience_Required,Salary,Location,Skills_Required,Posted_Date,Job_Description,Company_Rating,Reviews_Count,Job_Type,Company_Size,Industry,Apply_Link
0,TimesJobs,data-analyst,KEY ACCOUNT MANAGER - INTERNATIONAL LOCATIONS,Megasphere Trader,Yrs,21 Yrs 0.75 - 0.95 LPA,None,None,Posted on: 19-05-2026,KEY ACCOUNT MANAGER - INTERNATIONAL LOCATIONS ...,None,None,None,None,None,https://www.timesjobs.com/job-detail/key-accou...
1,TimesJobs,data-analyst,Risk Analyst,Numerouno,Yrs,- 9 Yrs 5.05 - 9.05 LPA,None,None,Posted on: 21-05-2026,Risk Analyst Numerouno | Posted on: 21-05-202...,None,None,None,None,None,https://www.timesjobs.com/job-detail/risk-anal...
2,TimesJobs,data-analyst,"Voice President , Sales Marketing",Sansom Insurance Brokers Pvt Ltd,Yrs,- 8 Yrs 4.50 - 6.00 LPA,None,None,Posted on: 21-05-2026,"Voice President , Sales Marketing Sansom Insur...",None,None,None,None,None,https://www.timesjobs.com/job-detail/voice-pre...
3,TimesJobs,data-analyst,CathLab Technician,Platinum Hospitals Pvt Ltd,Yrs,3 Yrs 15.00 - 25.00 LPA,None,None,Posted on: 22-05-2026,CathLab Technician Platinum Hospitals Pvt Ltd ...,None,None,None,None,None,https://www.timesjobs.com/job-detail/cathlab-t...
4,TimesJobs,data-analyst,HR Recruiter,EEPIC Management,Yrs,- 3 Yrs 1.01 - 2.00 LPA,None,None,Posted on: 22-05-2026,HR Recruiter EEPIC Management | Posted on: 22...,None,None,None,None,None,https://www.timesjobs.com/job-detail/hr-recrui...

In [36]:
#  Remove duplicate rows

df.drop_duplicates(inplace=True)


# Remove rows with missing critical fields

df.dropna(
    subset=[
        "Job_Title",
        "Company_Name"
        
    ],
    inplace=True
)


# Clean important text columns

text_cols = [

    "Portal_Name",

    "Role_Search",

    "Job_Title",

    "Company_Name",

    "Experience_Required",

    "Salary",

    "Location",

    "Skills_Required",

    "Posted_Date",

    "Job_Description",

    "Company_Rating",

    "Reviews_Count",

    "Job_Type",

    "Company_Size",

    "Industry",

    "Apply_Link"
]


for col in text_cols:

    df[col] = (
        df[col]
        .astype(str)
        .str.strip()
    )


# Replace 'None' strings with actual null values

df.replace(
    ["None", "nan", ""],
    pd.NA,
    inplace=True
)


# Reset dataframe index

df.reset_index(
    drop=True,
    inplace=True
)


# Check final dataset shape

print(df.shape)


# Check missing values

print(df.isnull().sum())


# Preview dataset

df.head()

(190, 16)
Portal_Name              0
Role_Search              0
Job_Title                0
Company_Name             0
Experience_Required      0
Salary                  48
Location               190
Skills_Required        190
Posted_Date              0
Job_Description          0
Company_Rating         190
Reviews_Count          190
Job_Type               190
Company_Size           190
Industry               190
Apply_Link               0
dtype: int64

,Portal_Name,Role_Search,Job_Title,Company_Name,Experience_Required,Salary,Location,Skills_Required,Posted_Date,Job_Description,Company_Rating,Reviews_Count,Job_Type,Company_Size,Industry,Apply_Link
0,TimesJobs,data-analyst,KEY ACCOUNT MANAGER - INTERNATIONAL LOCATIONS,Megasphere Trader,Yrs,21 Yrs 0.75 - 0.95 LPA,<NA>,<NA>,Posted on: 19-05-2026,KEY ACCOUNT MANAGER - INTERNATIONAL LOCATIONS ...,<NA>,<NA>,<NA>,<NA>,<NA>,https://www.timesjobs.com/job-detail/key-accou...
1,TimesJobs,data-analyst,Risk Analyst,Numerouno,Yrs,- 9 Yrs 5.05 - 9.05 LPA,<NA>,<NA>,Posted on: 21-05-2026,Risk Analyst Numerouno | Posted on: 21-05-202...,<NA>,<NA>,<NA>,<NA>,<NA>,https://www.timesjobs.com/job-detail/risk-anal...
2,TimesJobs,data-analyst,"Voice President , Sales Marketing",Sansom Insurance Brokers Pvt Ltd,Yrs,- 8 Yrs 4.50 - 6.00 LPA,<NA>,<NA>,Posted on: 21-05-2026,"Voice President , Sales Marketing Sansom Insur...",<NA>,<NA>,<NA>,<NA>,<NA>,https://www.timesjobs.com/job-detail/voice-pre...
3,TimesJobs,data-analyst,CathLab Technician,Platinum Hospitals Pvt Ltd,Yrs,3 Yrs 15.00 - 25.00 LPA,<NA>,<NA>,Posted on: 22-05-2026,CathLab Technician Platinum Hospitals Pvt Ltd ...,<NA>,<NA>,<NA>,<NA>,<NA>,https://www.timesjobs.com/job-detail/cathlab-t...
4,TimesJobs,data-analyst,HR Recruiter,EEPIC Management,Yrs,- 3 Yrs 1.01 - 2.00 LPA,<NA>,<NA>,Posted on: 22-05-2026,HR Recruiter EEPIC Management | Posted on: 22...,<NA>,<NA>,<NA>,<NA>,<NA>,https://www.timesjobs.com/job-detail/hr-recrui...

In [37]:
# final cleaned dataset

df.to_csv(
    "../data/cleaned/timesjobs_final_dataset.csv",
    index=False
)

print("Final TimesJobs dataset exported successfully")

Final TimesJobs dataset exported successfully