In [1]:
# Step 1 - Import Required Libraries

import pandas as pd
import numpy as np
import re
from datetime import datetime

In [2]:
# Step 2 - Load Master Combined Dataset

df = pd.read_csv("../data/cleaned/master_jobs_dataset.csv")

df.head()

C:\Users\monis\AppData\Local\Temp\ipykernel_15028\3099909381.py:3: DtypeWarning: Columns (11,12,13) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/cleaned/master_jobs_dataset.csv")

,portal_name,role_search,job_title,company_name,experience_required,salary,location,skills_required,posted_date,job_description,company_rating,reviews_count,apply_link,source_job_id,currency,company_id,minimum_salary,maximum_salary,minimum_experience,maximum_experience
0,Naukri,data-analyst,Data Analyst,Capgemini,4-9 Yrs,NaN,"Hybrid - Chennai, Delhi / NCR, Mumbai (All Areas)","Power Bi, Data Analysis, Data Visualization, T...",1 day ago,Required Skills & Qualifications: . Bachelors ...,3.6,53623 Reviews,https://www.naukri.com/job-listings-data-analy...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Naukri,data-analyst,Data Analyst,Airtel Payments Bank,2-5 Yrs,NaN,Gurugram,"Power Bi, SQL, Python, Oracle SQL, Quicksight,...",1 week ago,"Job Description 1- Extract, analyze, and valid...",3.8,1463 Reviews,https://www.naukri.com/job-listings-data-analy...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Naukri,data-analyst,Data Analyst,Sbicap Securities,NaN,10-15 Lacs PA,Mumbai,"Data Analysis, Predictive Modeling, Statistica...",1 week ago,Key Competencies: . Strong proficiency in Pyth...,3.6,2287 Reviews,https://www.naukri.com/job-listings-data-analy...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Naukri,data-analyst,Data Analyst,Wonderla Holidays,3-5 Yrs,"50,000-80,000 PA",Bengaluru,"D2C, Google Data Studio, R, Google Analytics, ...",1 week ago,Preferred candidate profile,4.4,396 Reviews,https://www.naukri.com/job-listings-data-analy...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Naukri,data-analyst,Data Analyst,Snapdeal,1-6 Yrs,NaN,Gurugram,"master data, python, metadata, data analysis, ...",3+ weeks ago,Providing technical expertise in data storage ...,3.7,668 Reviews,https://www.naukri.com/job-listings-data-analy...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# Standardize Posted Date Column

from datetime import datetime, timedelta

today = datetime.today()

def convert_posted_date(value):

    if pd.isna(value):
        return pd.NaT

    value = str(value).lower().strip()

    try:

        if "day" in value:

            number = re.findall(r'\d+', value)

            if number:
                days = int(number[0])
                return today - timedelta(days=days)

        elif "week" in value:

            number = re.findall(r'\d+', value)

            if number:
                weeks = int(number[0])
                return today - timedelta(weeks=weeks)

        elif "month" in value:

            number = re.findall(r'\d+', value)

            if number:
                months = int(number[0])
                return today - timedelta(days=months * 30)

    except:
        return pd.NaT

    return pd.NaT


df["posted_date"] = df["posted_date"].apply(convert_posted_date)

print(df["posted_date"].head())

0   2026-05-23 13:19:06.236498
1   2026-05-17 13:19:06.236498
2   2026-05-17 13:19:06.236498
3   2026-05-17 13:19:06.236498
4   2026-05-03 13:19:06.236498
Name: posted_date, dtype: datetime64[ns]

In [4]:
# Step 3 - Standardize Job Roles


def standardize_role(title):

    title = str(title).lower()

    if "data analyst" in title:
        return "Data Analyst"

    elif "business analyst" in title:
        return "Business Analyst"

    elif "data scientist" in title:
        return "Data Scientist"

    elif "machine learning" in title or "ml engineer" in title:
        return "ML Engineer"

    elif "data engineer" in title:
        return "Data Engineer"

    elif "power bi" in title or "bi analyst" in title:
        return "BI Analyst"

    elif "python developer" in title:
        return "Python Developer"

    elif "selenium" in title or "sdet" in title or "automation tester" in title:
        return "QA Automation Engineer"

    elif "devops" in title:
        return "DevOps Engineer"

    elif "cloud engineer" in title:
        return "Cloud Engineer"

    elif "frontend" in title:
        return "Frontend Developer"

    elif "backend" in title:
        return "Backend Developer"

    elif "full stack" in title:
        return "Full Stack Developer"

    else:
        return "Others"


df["standardized_role"] = df["job_title"].apply(standardize_role)

print(df["standardized_role"].value_counts())

standardized_role
Others                    95943
Data Engineer              1520
Full Stack Developer       1515
DevOps Engineer            1146
QA Automation Engineer     1018
Business Analyst            938
Data Analyst                751
Data Scientist              740
Python Developer            580
BI Analyst                  534
Backend Developer           423
Cloud Engineer              422
ML Engineer                 340
Frontend Developer          158
Name: count, dtype: int64

In [5]:
# Step 4 - Skill Feature Engineering

skills = [
    "python",
    "sql",
    "power bi",
    "tableau",
    "excel",
    "selenium",
    "aws",
    "azure",
    "gcp",
    "java",
    "spark",
    "hadoop",
    "docker",
    "kubernetes",
    "jira",
    "jenkins",
    "rest api",
    "testng",
    "power apps"
]

for skill in skills:

    column_name = skill.replace(" ", "_") + "_flag"

    df[column_name] = df["skills_required"].str.lower().apply(
        lambda x: 1 if skill in str(x) else 0
    )

print(df.head())

  portal_name   role_search     job_title          company_name  \
0      Naukri  data-analyst  Data Analyst             Capgemini
1      Naukri  data-analyst  Data Analyst  Airtel Payments Bank
2      Naukri  data-analyst  Data Analyst     Sbicap Securities
3      Naukri  data-analyst  Data Analyst     Wonderla Holidays
4      Naukri  data-analyst  Data Analyst              Snapdeal

  experience_required            salary  \
0             4-9 Yrs               NaN
1             2-5 Yrs               NaN
2                 NaN     10-15 Lacs PA
3             3-5 Yrs  50,000-80,000 PA
4             1-6 Yrs               NaN

                                            location  \
0  Hybrid - Chennai, Delhi / NCR, Mumbai (All Areas)
1                                           Gurugram
2                                             Mumbai
3                                          Bengaluru
4                                           Gurugram

                                     skills_required  \
0  Power Bi, Data Analysis, Data Visualization, T...
1  Power Bi, SQL, Python, Oracle SQL, Quicksight,...
2  Data Analysis, Predictive Modeling, Statistica...
3  D2C, Google Data Studio, R, Google Analytics, ...
4  master data, python, metadata, data analysis, ...

                 posted_date  \
0 2026-05-23 13:19:06.236498
1 2026-05-17 13:19:06.236498
2 2026-05-17 13:19:06.236498
3 2026-05-17 13:19:06.236498
4 2026-05-03 13:19:06.236498

                                     job_description  ...  java_flag  \
0  Required Skills & Qualifications: . Bachelors ...  ...          0
1  Job Description 1- Extract, analyze, and valid...  ...          0
2  Key Competencies: . Strong proficiency in Pyth...  ...          0
3                        Preferred candidate profile  ...          0
4  Providing technical expertise in data storage ...  ...          0

  spark_flag hadoop_flag docker_flag kubernetes_flag  jira_flag  jenkins_flag  \
0          0           0           0               0          0             0
1          0           0           0               0          0             0
2          0           0           0               0          0             0
3          0           0           0               0          0             0
4          0           0           0               0          0             0

   rest_api_flag  testng_flag  power_apps_flag
0              0            0                0
1              0            0                0
2              0            0                0
3              0            0                0
4              0            0                0

[5 rows x 40 columns]

In [10]:
# Step 5 - Create Total Skills Count

skill_columns = [col for col in df.columns if "_flag" in col]

df["total_skills"] = df[skill_columns].sum(axis=1)

print(df["total_skills"].head())

0    3
1    3
2    2
3    2
4    1
Name: total_skills, dtype: int64

In [11]:
# Step 6 - Date Feature Engineering

df["posted_date"] = pd.to_datetime(
    df["posted_date"],
    errors="coerce",
    dayfirst=True
)

df["posting_month"] = df["posted_date"].dt.month_name()

df["posting_year"] = df["posted_date"].dt.year

df.head()

,portal_name,role_search,job_title,company_name,experience_required,salary,location,skills_required,posted_date,job_description,...,jira_flag,jenkins_flag,rest_api_flag,testng_flag,power_apps_flag,total_skills,posting_month,posting_year,jd_length,urgent_hiring_flag
0,Naukri,data-analyst,Data Analyst,Capgemini,4-9 Yrs,NaN,"Hybrid - Chennai, Delhi / NCR, Mumbai (All Areas)","Power Bi, Data Analysis, Data Visualization, T...",2026-05-23 13:19:06.236498,Required Skills & Qualifications: . Bachelors ...,...,0,0,0,0,0,3,May,2026.0,90,0
1,Naukri,data-analyst,Data Analyst,Airtel Payments Bank,2-5 Yrs,NaN,Gurugram,"Power Bi, SQL, Python, Oracle SQL, Quicksight,...",2026-05-17 13:19:06.236498,"Job Description 1- Extract, analyze, and valid...",...,0,0,0,0,0,3,May,2026.0,89,0
2,Naukri,data-analyst,Data Analyst,Sbicap Securities,NaN,10-15 Lacs PA,Mumbai,"Data Analysis, Predictive Modeling, Statistica...",2026-05-17 13:19:06.236498,Key Competencies: . Strong proficiency in Pyth...,...,0,0,0,0,0,2,May,2026.0,90,0
3,Naukri,data-analyst,Data Analyst,Wonderla Holidays,3-5 Yrs,"50,000-80,000 PA",Bengaluru,"D2C, Google Data Studio, R, Google Analytics, ...",2026-05-17 13:19:06.236498,Preferred candidate profile,...,0,0,0,0,0,2,May,2026.0,27,0
4,Naukri,data-analyst,Data Analyst,Snapdeal,1-6 Yrs,NaN,Gurugram,"master data, python, metadata, data analysis, ...",2026-05-03 13:19:06.236498,Providing technical expertise in data storage ...,...,0,0,0,0,0,1,May,2026.0,90,0

In [12]:
# Step 7 - Job Description Features

df["jd_length"] = df["job_description"].astype(str).apply(len)

df["urgent_hiring_flag"] = df["job_description"].str.lower().apply(
    lambda x: 1 if "immediate joiner" in str(x) else 0
)

df.head()

,portal_name,role_search,job_title,company_name,experience_required,salary,location,skills_required,posted_date,job_description,...,jira_flag,jenkins_flag,rest_api_flag,testng_flag,power_apps_flag,total_skills,posting_month,posting_year,jd_length,urgent_hiring_flag
0,Naukri,data-analyst,Data Analyst,Capgemini,4-9 Yrs,NaN,"Hybrid - Chennai, Delhi / NCR, Mumbai (All Areas)","Power Bi, Data Analysis, Data Visualization, T...",2026-05-23 13:19:06.236498,Required Skills & Qualifications: . Bachelors ...,...,0,0,0,0,0,3,May,2026.0,90,0
1,Naukri,data-analyst,Data Analyst,Airtel Payments Bank,2-5 Yrs,NaN,Gurugram,"Power Bi, SQL, Python, Oracle SQL, Quicksight,...",2026-05-17 13:19:06.236498,"Job Description 1- Extract, analyze, and valid...",...,0,0,0,0,0,3,May,2026.0,89,0
2,Naukri,data-analyst,Data Analyst,Sbicap Securities,NaN,10-15 Lacs PA,Mumbai,"Data Analysis, Predictive Modeling, Statistica...",2026-05-17 13:19:06.236498,Key Competencies: . Strong proficiency in Pyth...,...,0,0,0,0,0,2,May,2026.0,90,0
3,Naukri,data-analyst,Data Analyst,Wonderla Holidays,3-5 Yrs,"50,000-80,000 PA",Bengaluru,"D2C, Google Data Studio, R, Google Analytics, ...",2026-05-17 13:19:06.236498,Preferred candidate profile,...,0,0,0,0,0,2,May,2026.0,27,0
4,Naukri,data-analyst,Data Analyst,Snapdeal,1-6 Yrs,NaN,Gurugram,"master data, python, metadata, data analysis, ...",2026-05-03 13:19:06.236498,Providing technical expertise in data storage ...,...,0,0,0,0,0,1,May,2026.0,90,0

In [13]:
# Step 8 - Save Final Engineered Dataset

df.to_csv("../data/cleaned/final_engineered_jobs_dataset.csv", index=False)

print("Feature Engineering Completed")

Feature Engineering Completed